### ISSUE TITLE
mip2中的CSS里会有fontsize为100px的样式，此样式在站长改MIP2的时候，会涉及到样式错乱问题

### ISSUE THREAD

**Issue by Espoir-L** [mipengine/mip2#182]
**要解决什么问题**
mip2中的CSS里会有fontsize为100px的样式，此样式在站长把站点从mip1改造成mip2的时候，会导致到样式错乱问题，需要重新修改网页的样式

**描述一下你理想中的解决方案**
不知道是否可以把这块的样式去掉，因为个人理解，当站长在迁移mip2的时候，可能对此问题是未知的，如果直接操作上线，会引起线上的样式错乱问题，即使对此问题是已知的，还需要对页面进行修改，现有站点较多，如果有站点升级就要修改样式，感觉成本还是有的。

**描述你的备选方案**
清晰准确的描述你考虑的备选方案

**补充信息**
补充其他信息，如截图等

**Comment by PengXing** [comment]
我不太懂是什么意思？是指 rem 吗？

**Comment by Espoir-L** [comment]
不是rem。是全局的fontsize为100px后，有些站长在原有的mip1的基础上直接改成了mip2的js和css以后，发现站点的字体变得很大，样式有些错乱。

**Comment by PengXing** [comment]
html 标签写了 100px，但是在 body 里面也设置了 14px，能给我个有问题的我看看吗

```css
body {
  font-size-adjust: none;
  -webkit-text-size-adjust: none;
  text-size-adjust: none;
  font: 14px Arial,Helvetica,sans-serif;
  box-sizing: border-box;
  -webkit-box-sizing: border-box;
}
```
