### ISSUE TITLE
MIP 页面内容宽度

### ISSUE THREAD

**Issue by xiaoiver** [mipengine/mip2#216]
**BUG 描述**
MIP 页面中的元素内容宽度如果超出，会导致整个页面宽度被撑开，由于 `<mip-shell>` 中的 header 或者是用户自定义的 `<mip-footer>` 都会使用 `width: 100%`，就会出现截图中的效果。

**期望结果**
线上的 MIP 官网使用了 `<style mip-custom>` 添加了样式：
```css
body {
    text-align: left;
    color: #333;
    line-height: 1.6;
    background-color: #f2f2f2;
    font-family: -apple-system,"Helvetica Neue",Arial,"PingFang SC","Hiragino Sans GB",STHeiti,"Microsoft YaHei","Microsoft JhengHei","Source Han Sans SC",SimSun,sans-serif;
    overflow-x: hidden;
}
```

所以在 MIP 页面基础样式上加上就 OK 了。

**截图**
![96d04a049adaf03d3f6c68ad793c8299](https://user-images.githubusercontent.com/3608471/44695706-0c742a00-aaa7-11e8-89bf-ed2dd77e2ab8.png)

**环境及版本信息:**
 - OS: iOS
 - Browser 手百
