### ISSUE TITLE
反馈:docs/components/layout/mip-nav-slidedown.md

### ISSUE THREAD

**Issue by tanice** [mipengine/mip2#501]
data-showbrand 设为0时 data-brandname依旧显示 V2版本

**Comment by clark-t** [comment]
已知问题，年后上线修复。
目前请暂时通过以下样式进行覆盖：
```css
.navbar-brand {
  display: none;
}
```
